name: Integration Test
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  test-opencode:
    if: "!github.event.pull_request.draft"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          opencode_api_key: ${{ secrets.OPENCODE_API_KEY }}
